import React from 'react'

const DoctorsInfo = () => {
  return (
    <div className='docInfo'>
        <div className='docInfo__heading'>
            <h1 className='docInfo__head1'>THE BEST</h1>
            <h2 className='docInfo__head2'>DOCTORS FIVES</h2>
            <h3 className='docInfo__head3'>THE LEAST MEDICINE</h3>
        </div>
        <div className='docInfo__whole'>
            <div className='docInfo__InsideText'>
            <h5>What is online doctor consultation?</h5>
            <p>Online doctor consultation or ‘telemedicine’ is the provision of clinical services like appointment, diagnosis, treatment, prescription, and follow-ups using communication technology. You do away with the need of visiting the hospital or the doctor’s office and access healthcare through video, chat, call, phone, or email. Online healthcare services started during the early 2000s and given factors like the penetration of technology, people becoming more cognizant of their health, and wanting to save time that would have otherwise been lost waiting and travelling, it has only seen an upward growth. Online doctor consultation has significantly contributed to improving health outcomes for people and is beneficial for not only the patient but for the doctor also. You can now consult doctor online through the Cult.fit website or mobile application. It has never been simpler or seamless before to get a quick and easy medical consultation. We serve as a conduit between people looking for healthcare services and the country’s most credible and trusted hospital chains and practitioners to prioritize healthcare and making it accessible and affordable. It is a great way to reach patients who live in rural areas or who may not be able to access healthcare for any reason.</p>
            <h5>How to Consult a Doctor Online?</h5>
            <p>The process of online medical consultation is extremely simple and accelerates the time within which you receive medical support from seeking an appointment to getting a treatment. Once you decide to consult doctor online, you just need to follow these simple steps: Digitize your medical reports and records to share them before you consult doctor online. Book an appointment for online medical consultation with the doctor of your choice depending on the condition or symptoms that you are experiencing. You can do this via our website or by downloading our mobile application and reach our to the top specialists in the country. Pay for your online doctor consultation after which you will receive the confirmation for your appointment. Share your reports with the doctor to help them understand your case in detail before your appointment day. Before your appointment, jot down all the symptoms and questions that you may have. This is done to avoid missing out on any important points and to make the best use of the time allotted to you. During your chat with a doctor, she/he will do a comprehensive investigation of your case and recommend the best line of treatment and the follow-up date, if required.</p>
            <h5>Which doctor specialities are available for an online consultation?</h5>
            <p>You can connect and consult doctors online across 20 + specialities spread over a range of health concerns over voice & video calls and chat at Cult.fit. These include: Specialists: Internal/ family medicine, Gynaecologist, Orthopaedist, Dermatologist (Skin Specialist), ENT (Ear Nose Throat), Sexologist, Ophthalmologist (Eye Specialist), Paediatric (Child Specialist), Urologist, Dentist, Trichologist (Hair Specialist), Physiotherapist, Psychiatrist Super-specialists: Endocrinologist, Gastroenterologist, Pulmonologist, Neurologist, Cardiologist (Heart Specialist), Rheumatologist, Nephrologist, Oncologist. Other experts and consultants available on our platform: Nutritionist/Ayurveda Doctors/Therapists</p>
            <h5>Is a video consultation option available?</h5>
            <p>Yes, Cult.fit offers on-demand online doctor consultation services through video calling. This is the perfect way to get a personal assessment without having to visit a clinic or hospital. And it is very easy to use too. You simply need to register yourself on our website or mobile application and create a profile and consult doctor online.</p>
            <h5>Cost of online doctor consultation</h5>
            <p>The cost of online doctor consultation services starts at a flat Rs. 149. However, it depends on the personalised treatment that you may be advised and the number of consultations that you need to attend. Coming Soon : Your personalised sugar.fit program to help you reduce your diabetic sugar levels in a simple, specific and sustainable way!</p>
            <h5>Top Searches</h5>
            <p>Online Workout Classes</p>
            <p>Cardio Exercises | Lean Muscle | Lean Body | Weight Loss Exercises | Six Pack Abs | HIIT Workout for Beginners | Exercise for Belly Fat | HRX Workout | Handstand Push Up | Online Fitness Trainer | How To Increase Stamina | Online Yoga Classes | Split Exercise | Workout For Beginners | Dumbbell Exercises | Pilates Workout | Walking Exercise | Pistol Squats | Oblique Exercises | Gym Near Me</p>
            <p>Mindfulness</p>
            
            </div>
                    
            <div className='docInfo__InsideText docInfo__sec'>
            <h5>What are the benefits of online doctor consultation?</h5>
            <p>With virtual access to healthcare becoming a reality through online doctor consultation, getting sound medical care is as easy as making a Skype call! There are several important benefits of online doctor consultation like: Online doctor consultation is available for the treatment of a range of issues that may be common or complex and acute or chronic. In your online doctor consultation, you get access to the country’s best speciality doctors for a personalised diagnosis and get the best possible healthcare advice. You are not limited to a specific clinic or hospital due to geographical boundaries in an online chat with doctor on Cult.fit. You can have an online chat with doctor while managing your schedule. The appointments can be scheduled on a day and time of your choice. You can chat with a doctor 24/7 without having to wait for the clinic or hospital to open the next day. You don’t need to travel for an online chat with doctor. Since the online doctor consultation is done virtually, it saves not only your time but also travel costs. This is especially beneficial for people who have busy schedules or those who have compromised mobility and travelling poses a risk of injuries or falls. Online doctor consultation is a great way to save costs. These include the cost of travel, parking, taking time off work, etc. Since you consult a doctor from the comfort, privacy, and convenience of your home, it helps in reducing stress and anxiety. When you are calm and relaxed, your chances of healing faster also increase. Online doctor consultation is a private and secure way to access healthcare. We ensure that not only your payments are transferred securely but your medical history, data, and information are also kept confidential when you consult doctor online. Online doctor consultation saves you from the risk of infections that you would otherwise be exposed to in a clinic. This is one of the most important advantages of doctor video consultation for people who have weak immunities. A doctor video consultation is as good as meeting a doctor in person. You can see her/him and hear their voice that gives you a feeling of the doctor being personally involved in your treatment. With our online doctor consultation services, you can avail of several incentives like one free follow up with every consultation, discounts on consultation fee, easy rescheduling, and cancellations. You learn self-care when you consult doctor online. Since you are the one elucidating your symptoms and explaining your triggers, you get educated about your health by default. The doctor also teaches you how to take care of yourself in between appointments. Timely and personalised access to healthcare through online doctor consultation can help arrest smaller health issues in time before they become larger problems.</p>

            <p>Yoga Asanas | Yoga For Weight Loss | Kids Yoga | Surya Namaskar | Yoga | Yoga For Beginners | Yoga Nidra | Music Meditation | Pranayam | Bedtime Stories | Bedtime Stories For Kids | Mindfulness Meditation | Meditation in Hindi | Sleep Meditation | Meditation</p>
            <p>Online Doctor Consultation & Diagnostic Tests</p>
            <p>Dentist Near Me | Gynaecologist Near Me | Dermatologist Near Me | Endocrinologist Near Me | Pulmonologist Near Me | Cardiologist Near Me | Orthopedist Doctor Near Me | Thyroid Test | Pregnancy Test | Full Body Checkup | Kidney Function Test | Therapist Near Me | Online Counselling | Physiotherapist Near Me</p>
            <p>Healthy Recipes</p>
            <p>Sambar Recipe | Masala For Dosa | Kadai Paneer Recipe | Mattar Paneer Recipe | Manchow Soup | Egg Curry | Chilli Baby Corn | Homemade Protein Powder | Veg Thukpa | Double Ka Meetha</p>
            <p>Gyms In India</p>
            <p>Gyms In Delhi | Gyms In Mumbai | Gyms In Bangalore | Gyms In Pune | Gyms In Chennai | Gyms In Hyderabad | Gyms In Jaipur | Gyms In Kolkata | Gyms In Ahmedabad | Gyms In Chandigarh | Gyms In Indore | Gyms In Coimbatore | Gyms In Surat | Gyms In Ludhiana | Gyms In Vizag | Gyms In Amritsar | Gyms In Mysore | Gyms In Mangalore | Gyms In Kochi | Gyms In Jammu | Gym In Kharghar | Gym In Bandra | Gym In Velachery | Gym In Chembur | Gym In Indiranagar | Gym In HSR Layout</p>

            </div>

        </div>
    </div>
  )
}

export default DoctorsInfo