export { default as Navbar } from "./Navbar/Navbar";
export { default as Home } from "./Home/Home";
export { default as Care } from "./Care/Care";
export { default as Fitness } from "./Fitness/Fitness";
export { default as Store } from "./Store/Store";
export { default as Mind } from "./Mind/Mind";
export { default as Footer } from "./Footer/Footer";
export { default as Login } from "./Login/Login";
export { default as Cart } from "./Cart/Cart";
export { default as Product } from "./Product/Product";
export { default as Error } from "./Error/Error"
export { default as Checkout } from "./Checkout/Checkout";
